### ISSUE TITLE
[Bug] Ghast rename breaks texture

### ISSUE THREAD

**Issue by Gilberry** [Stardust-Labs-MC/Incendium-Optional-Resourcepack#5]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

v5.3.7

### Mod or datapack version?

Datapack

### Describe the bug

Since the name of the sentry was changed from "Reactor Sentry" to "Ghast Sentry" the custom sentry texture is no longer applied in the nether reactor.

**Comment by catter1** [comment]
Fixed in some version ago
